# Dockerfile.dev (for development)
FROM node:22-alpine

# Install build dependencies
RUN apk add --no-cache python3 make g++ bash

# Create app directory
WORKDIR /usr/src/app

# Install nodemon globally
RUN npm install -g nodemon

# Install app dependencies
COPY package*.json ./
RUN npm install

# Expose port
EXPOSE 3000

# Start with nodemon for hot reload
CMD ["nodemon", "src/server.js"]